name: Release and Publish to crates.io

on:
  push:
    tags: ['v*']  # Triggers when pushing tags starting with 'v'
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release  # For enhanced security
    permissions:
      id-token: write     # Required for OIDC token exchange
      contents: read      # Required to checkout code
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        
    - name: Verify workspace builds
      run: |
        cargo check --workspace --verbose
        cargo test --workspace --verbose
        
    - name: Authenticate with crates.io
      uses: rust-lang/crates-io-auth-action@v1
      id: auth
      
    - name: Publish casial-core
      run: |
        cd crates/casial-core
        cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        
    - name: Wait for casial-core availability
      run: |
        echo "Waiting for casial-core to be available on crates.io..."
        sleep 60  # Wait for crate to be indexed
        
    - name: Publish casial-server
      run: |
        cd crates/casial-server
        cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        
    - name: Wait for casial-server availability  
      run: |
        echo "Waiting for casial-server to be available..."
        sleep 60
        
    - name: Publish casial-wasm
      run: |
        cd crates/casial-wasm
        cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## Context-Casial-Xpress ${{ github.ref_name }}
          
          **Consciousness-aware context coordination for AI agent systems**
          
          ### Published Crates
          - `casial-core` - Core consciousness-aware coordination engine
          - `casial-server` - High-performance WebSocket MCP server  
          - `casial-wasm` - WASM bindings for universal deployment
          
          ### Installation
          ```bash
          # Core library (MIT/Apache-2.0)
          cargo add casial-core
          
          # Server binary (Fair Use license)
          cargo install casial-server
          
          # WASM bindings (Fair Use license)  
          cargo add casial-wasm
          ```
          
          See [LICENSE.md](LICENSE.md) for Fair Use license terms.
          Commercial licensing: breyden@prompted.community
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}